### ISSUE TITLE
Path problem including graphql files

### ISSUE THREAD

**Issue by Kisepro** [detrohutt/babel-plugin-import-graphql#50] opened 2018-11-25 21:04 UTC
Hello,

When I try to simply import a gql file, I always get the error : 

```
error: bundling failed: Error: Cannot find module './myQuery.gql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at PluginPass.exit (C:\Project\importGQL\node_modules\babel-plugin-import-graphql\build\index.js:72:66)
    at newFn (C:\Project\importGQL\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\Project\importGQL\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Project\importGQL\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Project\importGQL\node_modules\@babel\traverse\lib\path\context.js:97:8)
    at TraversalContext.visitQueue (C:\Project\importGQL\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\Project\importGQL\node_modules\@babel\traverse\lib\context.js:85:17)

```
### My code : 

`import Query from "./myQuery.gql";`

![image](https://user-images.githubusercontent.com/7433141/48984622-38329a80-f0fe-11e8-8c7f-7fac93742ccd.png)

The only way to make it **working** is to use the **absolute** path to the graphql path. ex : C:\Project\importGQL\components\myQuery.gql

### Reproduction
I reproduce it on a simple project : https://github.com/Kisepro/importGQLBug.git

### Investigation
When I check in babel-plugin-import-graphql\build\index.js, it calls the function with the following parameters  :   

- importPath ./Query.gql

- jsFilename C:\Project\importGQL\node_modules\react-native\scripts\components\ComponentA.js

The ComponentA.js file is obviously not in under node_modules

**Comment by amwill04** [comment] 2019-01-08 10:47
The issue seems to be the fact that `jsFilepath` is resolving to `node_modules/react-natve/components/ComponentA` and therefore `babel-plugin-import-graphql` can't resolve `./myQuery`. Using `nodePath opt` I first thought would solve the issue but it doesn't as it means you can't have duplicate file names in different directories.

I have tried using `babel-plugin-module-resolver` to get the correct `cwd` and/or `root` but have no success with that it keeps giving the root being `node_modules/react-native`.

Ive basically given up trying to use this to import static `graphql` files until I get more time to look at it - resolved to simply using `graphql-tag` in `js` files.

**Comment by jameskennethrobinson** [comment] 2019-02-14 20:28
This is also a problem for me.

**Comment by detrohutt** [comment] 2019-03-03 18:26
Were any of you who experienced this problem *not* using react-native? I've got too much going on to set up and mess with react-native, but if anyone can offer a reproduction of this problem that doesn't involve react-native I can take a look. Pull requests by anyone who uses react-native are also welcome. :)

**Comment by detrohutt** [comment] 2019-05-30 18:37
After seeing this mentioned in #48 as well, I believe @stephencaldwell is correct. I'm closing this. If anyone experiences this issue with the settings mentioned above, let me know and I'll reopen.

**Closed by detrohutt** 2019-05-30 18:37 UTC
Labels: react-native
