### ISSUE TITLE
Unexpected token, expected ";"

### ISSUE THREAD

**Issue by benjamin-halter** [detrohutt/babel-plugin-import-graphql#48] opened 2018-11-09 00:45 UTC
I'm trying to use this plugin with React Native but am stuck with this error:
<img width="497" alt="screen shot 2018-11-09 at 1 39 59 pm" src="https://user-images.githubusercontent.com/32251097/48235965-02ff2a80-e425-11e8-9952-9776ba80c82a.png">

Node version: 8.10
Plugin version: 2.6.2

My files are as such: 
.babelrc
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": ["react-native-paper/babel", "import-graphql"]
}
```

all-cattles.query.graphql 
```
query allCattles {
  listCattle {
    name
  }
}
```
Please let me know if there's anything else needed. Thanks

**Comment by detrohutt** [comment] 2018-11-09 01:10
Hey, thanks for trying my plugin! Are you using `create-react-native-app` or something else? I don't use react-native myself but if you can give me a rough idea of how you made your project (i.e. following a tutorial somewhere) I can try to make a reproduction later. It'll be at least a few days though because I'm currently quite sick.

**Comment by benjamin-halter** [comment] 2018-11-10 21:31
Thanks for getting back so quick. I'm using the native code guide here: https://facebook.github.io/react-native/docs/getting-started.html Thanks.

**Comment by detrohutt** [comment] 2018-11-16 14:10
Work has been a little crazy but I'm going to try to take a look at this over the weekend. :)

**Comment by jefflewis** [comment] 2019-05-30 18:30
I was seeing this, but incorrectly included `graphql` in my `sourceExts` instead of `assetExts` in my metro config as described here in https://github.com/detrohutt/babel-plugin-import-graphql/issues/50.

This worked for me:

```js
module.exports = {
  resolver: {
    assetExts: ["graphql", "gql", "png"],
  },
  transformer: {
    babelTransformerPath: require.resolve(
      "react-native-typescript-transformer"
    ),
    enableBabelRCLookup: true
  }
};
```

**Comment by detrohutt** [comment] 2019-05-30 18:39
I'm closing this for now since it's been open for almost 7 months and only has one +1. If the solution @jefflewis mentioned doesn't work for someone, and you get this same error, let me know and I'll reopen the issue.

**Closed by detrohutt** 2019-05-30 18:39 UTC
Labels: react-native
